/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 08 15:47:32 GMT 2017
 */

package collections.iterators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import collections.Predicate;
import collections.functors.InstanceofPredicate;
import collections.functors.TruePredicate;
import collections.functors.UniquePredicate;
import collections.iterators.FilterIterator;
import java.util.Collection;
import java.util.ConcurrentModificationException;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.ListIterator;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class FilterIterator_ESTest extends FilterIterator_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 27 covered goals:
   * Goal 1. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 2. collections.iterators.FilterIterator.hasNext()Z: Line 69
   * Goal 3. collections.iterators.FilterIterator.setNextObject()Z: Line 165
   * Goal 4. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: Line 118
   * Goal 5. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 6. collections.iterators.FilterIterator.hasNext()Z: Line 72
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 10. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch
   * Goal 11. collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true
   * Goal 12. collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false
   * Goal 13. hasNext()Z_java.util.ConcurrentModificationException_IMPLICIT
   * Goal 14. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 15. Weak Mutation 3: collections.iterators.FilterIterator.hasNext()Z:69 - InsertUnaryOp Negation
   * Goal 16. Weak Mutation 4: collections.iterators.FilterIterator.hasNext()Z:69 - ReplaceComparisonOperator == -> !=
   * Goal 17. Weak Mutation 16: collections.iterators.FilterIterator.setNextObject()Z:164 - ReplaceComparisonOperator == -> !=
   * Goal 18. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 19. [METHOD] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 20. [METHOD] collections.iterators.FilterIterator.hasNext()Z
   * Goal 21. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 22. [METHODNOEX] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 23. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 24. Branch collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch in context: collections.iterators.FilterIterator:getIterator()Ljava/util/Iterator;
   * Goal 25. Branch collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true in context: collections.iterators.FilterIterator:hasNext()Z
   * Goal 26. Branch collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false in context: 
   * Goal 27. [Output]: collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;:NonNull
   */

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<String> linkedList1 = new LinkedList<String>();
      linkedList1.add((String) null);
      linkedList1.add("");
      linkedList0.addAll((Collection<? extends String>) linkedList1);
      Iterator<String> iterator0 = linkedList0.descendingIterator();
      linkedList0.removeFirst();
      linkedList0.add("");
      FilterIterator filterIterator0 = new FilterIterator(iterator0);
      filterIterator0.getIterator();
      // Undeclared exception!
      try { 
        filterIterator0.hasNext();
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.LinkedList$ListItr", e);
      }
  }

  //Test case number: 1
  /*
   * 16 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 2. collections.iterators.FilterIterator.remove()V: Line 105
   * Goal 3. collections.iterators.FilterIterator.remove()V: Line 108
   * Goal 4. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 5. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 6. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 7. collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true
   * Goal 8. remove()V_java.lang.IllegalStateException_IMPLICIT
   * Goal 9. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 10. Weak Mutation 10: collections.iterators.FilterIterator.remove()V:105 - InsertUnaryOp Negation
   * Goal 11. Weak Mutation 11: collections.iterators.FilterIterator.remove()V:105 - ReplaceComparisonOperator == -> !=
   * Goal 12. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 13. [METHOD] collections.iterators.FilterIterator.remove()V
   * Goal 14. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 15. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 16. Branch collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true in context: collections.iterators.FilterIterator:remove()V
   */

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Iterator<String> iterator0 = linkedList0.descendingIterator();
      FilterIterator filterIterator0 = new FilterIterator(iterator0);
      // Undeclared exception!
      try { 
        filterIterator0.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.LinkedList$ListItr", e);
      }
  }

  //Test case number: 2
  /*
   * 14 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 2. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: Line 140
   * Goal 3. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 4. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 5. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch
   * Goal 6. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 7. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 8. [Output]: collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;:Null
   * Goal 9. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 10. [METHOD] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   * Goal 11. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 12. [METHODNOEX] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   * Goal 13. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 14. Branch collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch in context: collections.iterators.FilterIterator:getPredicate()Lcollections/Predicate;
   */

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Iterator<String> iterator0 = linkedList0.descendingIterator();
      FilterIterator filterIterator0 = new FilterIterator(iterator0);
      Predicate predicate0 = filterIterator0.getPredicate();
      assertNull(predicate0);
  }

  //Test case number: 3
  /*
   * 21 covered goals:
   * Goal 1. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 2. collections.iterators.FilterIterator.hasNext()Z: Line 69
   * Goal 3. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 4. collections.iterators.FilterIterator.hasNext()Z: Line 72
   * Goal 5. collections.iterators.FilterIterator.setNextObject()Z: Line 172
   * Goal 6. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 7. collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true
   * Goal 8. collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - true
   * Goal 9. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 10. Weak Mutation 3: collections.iterators.FilterIterator.hasNext()Z:69 - InsertUnaryOp Negation
   * Goal 11. Weak Mutation 4: collections.iterators.FilterIterator.hasNext()Z:69 - ReplaceComparisonOperator == -> !=
   * Goal 12. Weak Mutation 16: collections.iterators.FilterIterator.setNextObject()Z:164 - ReplaceComparisonOperator == -> !=
   * Goal 13. Weak Mutation 20: collections.iterators.FilterIterator.setNextObject()Z:172 - ReplaceConstant - 0 -> 1
   * Goal 14. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 15. [METHOD] collections.iterators.FilterIterator.hasNext()Z
   * Goal 16. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 17. [METHODNOEX] collections.iterators.FilterIterator.hasNext()Z
   * Goal 18. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 19. Branch collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true in context: collections.iterators.FilterIterator:hasNext()Z
   * Goal 20. Branch collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - true in context: 
   * Goal 21. [Output]: collections.iterators.FilterIterator.hasNext()Z:False
   */

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      ListIterator<String> listIterator0 = linkedList0.listIterator();
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0);
      boolean boolean0 = filterIterator0.hasNext();
      assertFalse(boolean0);
  }

  //Test case number: 4
  /*
   * 13 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 2. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 3. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 4. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false
   * Goal 5. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   * Goal 6. Weak Mutation 6: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - InsertUnaryOp Negation
   * Goal 7. Weak Mutation 7: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - ReplaceComparisonOperator != -> ==
   * Goal 8. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 9. [METHOD] collections.iterators.FilterIterator.next()Ljava/lang/Object;
   * Goal 10. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 11. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 12. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 13. next()Ljava/lang/Object;_java.lang.NullPointerException_IMPLICIT
   */

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      // Undeclared exception!
      try { 
        filterIterator0.next();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("collections.iterators.FilterIterator", e);
      }
  }

  //Test case number: 5
  /*
   * 9 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 3. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch
   * Goal 4. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 5. collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true
   * Goal 6. [Output]: collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;:NonNull
   * Goal 7. [METHOD] collections.iterators.FilterIterator.hasNext()Z
   * Goal 8. Branch collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true in context: collections.iterators.FilterIterator:hasNext()Z
   * Goal 9. hasNext()Z_java.lang.NullPointerException_IMPLICIT
   */

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      FilterIterator filterIterator1 = new FilterIterator((Iterator) filterIterator0);
      Iterator iterator0 = filterIterator1.getIterator();
      TruePredicate truePredicate0 = (TruePredicate)TruePredicate.getInstance();
      FilterIterator filterIterator2 = new FilterIterator((Iterator) iterator0, (Predicate) truePredicate0);
      // Undeclared exception!
      try { 
        filterIterator2.hasNext();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("collections.iterators.FilterIterator", e);
      }
  }

  //Test case number: 6
  /*
   * 27 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 2. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: Line 118
   * Goal 3. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 150
   * Goal 4. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 151
   * Goal 5. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 6. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 152
   * Goal 7. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 153
   * Goal 8. collections.iterators.FilterIterator.remove()V: Line 105
   * Goal 9. collections.iterators.FilterIterator.remove()V: Line 108
   * Goal 10. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 11. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch
   * Goal 12. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: root-Branch
   * Goal 13. collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true
   * Goal 14. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   * Goal 15. Weak Mutation 10: collections.iterators.FilterIterator.remove()V:105 - InsertUnaryOp Negation
   * Goal 16. Weak Mutation 11: collections.iterators.FilterIterator.remove()V:105 - ReplaceComparisonOperator == -> !=
   * Goal 17. Weak Mutation 15: collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V:152 - ReplaceConstant - 0 -> 1
   * Goal 18. [Output]: collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;:Null
   * Goal 19. Branch collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true in context: collections.iterators.FilterIterator:remove()V
   * Goal 20. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 21. Branch collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch in context: collections.iterators.FilterIterator:getIterator()Ljava/util/Iterator;
   * Goal 22. Branch collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:setPredicate(Lcollections/Predicate;)V
   * Goal 23. [METHOD] collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V
   * Goal 24. [METHODNOEX] collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V
   * Goal 25. [METHOD] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 26. [METHODNOEX] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 27. remove()V_java.lang.NullPointerException_IMPLICIT
   */

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      UniquePredicate uniquePredicate0 = (UniquePredicate)UniquePredicate.getInstance();
      filterIterator0.setPredicate(uniquePredicate0);
      filterIterator0.setPredicate(uniquePredicate0);
      filterIterator0.getIterator();
      // Undeclared exception!
      try { 
        filterIterator0.remove();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("collections.iterators.FilterIterator", e);
      }
  }

  //Test case number: 7
  /*
   * 16 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 2. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 3. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 4. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 5. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 6. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 9. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 10. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 11. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 12. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 13. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 14. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 15. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 16. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   */

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Class<Object> class0 = Object.class;
      InstanceofPredicate instanceofPredicate0 = new InstanceofPredicate(class0);
      FilterIterator filterIterator0 = new FilterIterator((Iterator) null, (Predicate) instanceofPredicate0);
      FilterIterator filterIterator1 = new FilterIterator((Iterator) filterIterator0);
      assertFalse(filterIterator1.equals((Object)filterIterator0));
  }

  //Test case number: 8
  /*
   * 35 covered goals:
   * Goal 1. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 128
   * Goal 2. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 129
   * Goal 3. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 130
   * Goal 4. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 131
   * Goal 5. collections.iterators.FilterIterator.remove()V: Line 105
   * Goal 6. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: Line 140
   * Goal 7. collections.iterators.FilterIterator.remove()V: Line 108
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 12. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 13. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 14. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch
   * Goal 15. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 16. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 17. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: root-Branch
   * Goal 18. collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true
   * Goal 19. remove()V_java.util.ConcurrentModificationException_IMPLICIT
   * Goal 20. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 21. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 22. Weak Mutation 10: collections.iterators.FilterIterator.remove()V:105 - InsertUnaryOp Negation
   * Goal 23. Weak Mutation 11: collections.iterators.FilterIterator.remove()V:105 - ReplaceComparisonOperator == -> !=
   * Goal 24. Weak Mutation 14: collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V:130 - ReplaceConstant - 0 -> 1
   * Goal 25. [Output]: collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;:NonNull
   * Goal 26. Branch collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true in context: collections.iterators.FilterIterator:remove()V
   * Goal 27. Branch collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch in context: collections.iterators.FilterIterator:getPredicate()Lcollections/Predicate;
   * Goal 28. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 29. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 30. Branch collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:setIterator(Ljava/util/Iterator;)V
   * Goal 31. [METHOD] collections.iterators.FilterIterator.remove()V
   * Goal 32. [METHOD] collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V
   * Goal 33. [METHODNOEX] collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V
   * Goal 34. [METHOD] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   * Goal 35. [METHODNOEX] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   */

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      ListIterator<String> listIterator0 = linkedList0.listIterator();
      TruePredicate truePredicate0 = (TruePredicate)TruePredicate.INSTANCE;
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0, (Predicate) truePredicate0);
      TruePredicate truePredicate1 = (TruePredicate)filterIterator0.getPredicate();
      linkedList0.offer("6P3}u$3");
      linkedList0.subList(1, 1);
      filterIterator0.setIterator(listIterator0);
      FilterIterator filterIterator1 = new FilterIterator((Iterator) listIterator0, (Predicate) truePredicate1);
      FilterIterator filterIterator2 = new FilterIterator((Iterator) filterIterator0);
      FilterIterator filterIterator3 = new FilterIterator((Iterator) filterIterator2, (Predicate) truePredicate0);
      // Undeclared exception!
      try { 
        filterIterator0.remove();
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.LinkedList$ListItr", e);
      }
  }

  //Test case number: 9
  /*
   * 18 covered goals:
   * Goal 1. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 2. collections.iterators.FilterIterator.setNextObject()Z: Line 165
   * Goal 3. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 87
   * Goal 4. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 5. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 88
   * Goal 6. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 9. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false
   * Goal 10. collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false
   * Goal 11. Weak Mutation 16: collections.iterators.FilterIterator.setNextObject()Z:164 - ReplaceComparisonOperator == -> !=
   * Goal 12. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 13. Weak Mutation 6: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - InsertUnaryOp Negation
   * Goal 14. Weak Mutation 7: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - ReplaceComparisonOperator != -> ==
   * Goal 15. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 16. Branch collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false in context: 
   * Goal 17. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 18. next()Ljava/lang/Object;_java.util.ConcurrentModificationException_IMPLICIT
   */

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      ListIterator<String> listIterator0 = linkedList0.listIterator();
      linkedList0.addFirst("/sq%;s{3,WG");
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0);
      // Undeclared exception!
      try { 
        filterIterator0.next();
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.LinkedList$ListItr", e);
      }
  }

  //Test case number: 10
  /*
   * 41 covered goals:
   * Goal 1. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 2. collections.iterators.FilterIterator.hasNext()Z: Line 69
   * Goal 3. collections.iterators.FilterIterator.hasNext()Z: Line 72
   * Goal 4. collections.iterators.FilterIterator.setNextObject()Z: Line 172
   * Goal 5. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 6. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 7. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 87
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 9. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 88
   * Goal 10. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 89
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 12. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 13. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 14. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 15. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 16. collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true
   * Goal 17. collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - true
   * Goal 18. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false
   * Goal 19. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I9 Branch 3 IFNE L88 - false
   * Goal 20. Weak Mutation 16: collections.iterators.FilterIterator.setNextObject()Z:164 - ReplaceComparisonOperator == -> !=
   * Goal 21. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 22. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 23. Weak Mutation 3: collections.iterators.FilterIterator.hasNext()Z:69 - InsertUnaryOp Negation
   * Goal 24. Weak Mutation 4: collections.iterators.FilterIterator.hasNext()Z:69 - ReplaceComparisonOperator == -> !=
   * Goal 25. Weak Mutation 20: collections.iterators.FilterIterator.setNextObject()Z:172 - ReplaceConstant - 0 -> 1
   * Goal 26. Weak Mutation 6: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - InsertUnaryOp Negation
   * Goal 27. Weak Mutation 7: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - ReplaceComparisonOperator != -> ==
   * Goal 28. Weak Mutation 8: collections.iterators.FilterIterator.next()Ljava/lang/Object;:88 - ReplaceComparisonOperator != -> ==
   * Goal 29. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 30. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I9 Branch 3 IFNE L88 - false in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 31. Branch collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - true in context: 
   * Goal 32. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 33. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 34. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 35. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 36. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 37. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 38. [METHOD] collections.iterators.FilterIterator.next()Ljava/lang/Object;
   * Goal 39. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 40. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 41. next()Ljava/lang/Object;_java.util.NoSuchElementException_EXPLICIT
   */

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Iterator<String> iterator0 = linkedList0.descendingIterator();
      TruePredicate truePredicate0 = (TruePredicate)TruePredicate.INSTANCE;
      FilterIterator filterIterator0 = new FilterIterator((Iterator) iterator0, (Predicate) truePredicate0);
      FilterIterator filterIterator1 = new FilterIterator((Iterator) filterIterator0);
      // Undeclared exception!
      try { 
        filterIterator1.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("collections.iterators.FilterIterator", e);
      }
  }
}
