import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest1 {

    public static boolean debug = false;

    @Test
    public void test1() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test1");
        collections.map.DefaultedMap defaultedMap1 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set2 = defaultedMap1.keySet();
        boolean b4 = defaultedMap1.containsKey((java.lang.Object) 0.0f);
        java.util.Collection collection5 = defaultedMap1.values();
        java.lang.String str6 = defaultedMap1.toString();
        collections.Predicate predicate7 = null;
        collections.Predicate predicate8 = null;
        java.util.Map map9 = collections.map.PredicatedMap.decorate((java.util.Map) defaultedMap1, predicate7, predicate8);
        defaultedMap1.clear();
        org.junit.Assert.assertNotNull(set2);
        org.junit.Assert.assertTrue(b4 == false);
        org.junit.Assert.assertNotNull(collection5);
        org.junit.Assert.assertTrue("'" + str6 + "' != '" + "{}" + "'", str6.equals("{}"));
        org.junit.Assert.assertNotNull(map9);
    }

    @Test
    public void test2() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test2");
        collections.map.DefaultedMap defaultedMap1 = new collections.map.DefaultedMap((java.lang.Object) 0);
        java.lang.Object obj3 = defaultedMap1.remove((java.lang.Object) (byte) 100);
        collections.map.DefaultedMap defaultedMap5 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set6 = defaultedMap5.keySet();
        boolean b8 = defaultedMap5.containsKey((java.lang.Object) 0.0f);
        java.util.Collection collection9 = defaultedMap5.values();
        java.lang.Object obj11 = defaultedMap1.put((java.lang.Object) collection9, (java.lang.Object) 1);
        collections.map.DefaultedMap defaultedMap13 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set14 = defaultedMap13.keySet();
        boolean b16 = defaultedMap13.containsKey((java.lang.Object) 0.0f);
        java.util.Collection collection17 = defaultedMap13.values();
        collections.map.DefaultedMap defaultedMap18 = new collections.map.DefaultedMap((java.lang.Object) collection17);
        int i19 = defaultedMap18.size();
        collections.Predicate predicate20 = null;
        collections.Predicate predicate21 = null;
        java.util.Map map22 = collections.map.PredicatedMap.decorate((java.util.Map) defaultedMap18, predicate20, predicate21);
        collections.map.DefaultedMap defaultedMap24 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set25 = defaultedMap24.keySet();
        boolean b27 = defaultedMap24.containsKey((java.lang.Object) 0.0f);
        java.util.Collection collection28 = defaultedMap24.values();
        java.util.Set set29 = defaultedMap24.keySet();
        java.util.Set set30 = defaultedMap24.entrySet();
        java.lang.Object obj31 = defaultedMap1.put((java.lang.Object) predicate21, (java.lang.Object) defaultedMap24);
        collections.map.DefaultedMap defaultedMap33 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set34 = defaultedMap33.keySet();
        boolean b36 = defaultedMap33.containsKey((java.lang.Object) 0.0f);
        java.util.Collection collection37 = defaultedMap33.values();
        collections.Predicate predicate38 = null;
        collections.Predicate predicate39 = null;
        java.util.Map map40 = collections.map.PredicatedMap.decorate((java.util.Map) defaultedMap33, predicate38, predicate39);
        collections.map.DefaultedMap defaultedMap42 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj44 = defaultedMap42.remove((java.lang.Object) 1.0f);
        defaultedMap42.clear();
        collections.map.DefaultedMap defaultedMap47 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj49 = defaultedMap47.remove((java.lang.Object) 1.0f);
        collections.map.DefaultedMap defaultedMap51 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj53 = null;
        java.lang.Object obj54 = defaultedMap51.put((java.lang.Object) 1, obj53);
        boolean b56 = defaultedMap51.containsKey((java.lang.Object) 1);
        defaultedMap51.clear();
        java.lang.Object obj58 = defaultedMap42.put((java.lang.Object) defaultedMap47, (java.lang.Object) defaultedMap51);
        java.lang.Object obj59 = null;
        boolean b60 = defaultedMap47.containsValue(obj59);
        collections.map.DefaultedMap defaultedMap62 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        boolean b63 = defaultedMap62.isEmpty();
        boolean b64 = defaultedMap62.isEmpty();
        boolean b66 = defaultedMap62.equals((java.lang.Object) 10);
        java.lang.Object obj67 = defaultedMap47.get((java.lang.Object) b66);
        java.util.Map map68 = collections.map.DefaultedMap.decorate((java.util.Map) defaultedMap33, (java.lang.Object) defaultedMap47);
        collections.Predicate predicate69 = null;
        collections.Predicate predicate70 = null;
        java.util.Map map71 = collections.map.PredicatedMap.decorate((java.util.Map) defaultedMap33, predicate69, predicate70);
        boolean b72 = defaultedMap1.containsKey((java.lang.Object) predicate69);
        org.junit.Assert.assertNull(obj3);
        org.junit.Assert.assertNotNull(set6);
        org.junit.Assert.assertTrue(b8 == false);
        org.junit.Assert.assertNotNull(collection9);
        org.junit.Assert.assertNull(obj11);
        org.junit.Assert.assertNotNull(set14);
        org.junit.Assert.assertTrue(b16 == false);
        org.junit.Assert.assertNotNull(collection17);
        org.junit.Assert.assertTrue(i19 == 0);
        org.junit.Assert.assertNotNull(map22);
        org.junit.Assert.assertNotNull(set25);
        org.junit.Assert.assertTrue(b27 == false);
        org.junit.Assert.assertNotNull(collection28);
        org.junit.Assert.assertNotNull(set29);
        org.junit.Assert.assertNotNull(set30);
        org.junit.Assert.assertNull(obj31);
        org.junit.Assert.assertNotNull(set34);
        org.junit.Assert.assertTrue(b36 == false);
        org.junit.Assert.assertNotNull(collection37);
        org.junit.Assert.assertNotNull(map40);
        org.junit.Assert.assertNull(obj44);
        org.junit.Assert.assertNull(obj49);
        org.junit.Assert.assertNull(obj54);
        org.junit.Assert.assertTrue(b56 == true);
        org.junit.Assert.assertNull(obj58);
        org.junit.Assert.assertTrue(b60 == false);
        org.junit.Assert.assertTrue(b63 == true);
        org.junit.Assert.assertTrue(b64 == true);
        org.junit.Assert.assertTrue(b66 == false);
        org.junit.Assert.assertTrue("'" + obj67 + "' != '" + (byte) 0 + "'", obj67.equals((byte) 0));
        org.junit.Assert.assertNotNull(map68);
        org.junit.Assert.assertNotNull(map71);
        org.junit.Assert.assertTrue(b72 == true);
    }

    @Test
    public void test3() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test3");
        collections.map.DefaultedMap defaultedMap1 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set2 = defaultedMap1.keySet();
        java.util.Collection collection3 = defaultedMap1.values();
        collections.map.DefaultedMap defaultedMap5 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set6 = defaultedMap5.keySet();
        boolean b8 = defaultedMap5.containsKey((java.lang.Object) 0.0f);
        java.util.Collection collection9 = defaultedMap5.values();
        collections.map.DefaultedMap defaultedMap10 = new collections.map.DefaultedMap((java.lang.Object) collection9);
        boolean b11 = defaultedMap10.isEmpty();
        boolean b12 = defaultedMap1.containsValue((java.lang.Object) defaultedMap10);
        collections.map.DefaultedMap defaultedMap14 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set15 = defaultedMap14.keySet();
        boolean b17 = defaultedMap14.containsKey((java.lang.Object) 0.0f);
        java.util.Collection collection18 = defaultedMap14.values();
        collections.map.DefaultedMap defaultedMap19 = new collections.map.DefaultedMap((java.lang.Object) collection18);
        collections.map.DefaultedMap defaultedMap21 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj23 = defaultedMap21.remove((java.lang.Object) 1.0f);
        defaultedMap21.clear();
        collections.map.DefaultedMap defaultedMap26 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj28 = defaultedMap26.remove((java.lang.Object) 1.0f);
        collections.map.DefaultedMap defaultedMap30 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj32 = null;
        java.lang.Object obj33 = defaultedMap30.put((java.lang.Object) 1, obj32);
        boolean b35 = defaultedMap30.containsKey((java.lang.Object) 1);
        defaultedMap30.clear();
        java.lang.Object obj37 = defaultedMap21.put((java.lang.Object) defaultedMap26, (java.lang.Object) defaultedMap30);
        java.lang.Object obj38 = null;
        boolean b39 = defaultedMap26.containsValue(obj38);
        java.util.Set set40 = defaultedMap26.entrySet();
        java.lang.Object obj41 = defaultedMap19.remove((java.lang.Object) set40);
        collections.map.DefaultedMap defaultedMap43 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        boolean b44 = defaultedMap43.isEmpty();
        boolean b45 = defaultedMap43.isEmpty();
        java.lang.Object obj46 = defaultedMap10.put((java.lang.Object) defaultedMap19, (java.lang.Object) defaultedMap43);
        collections.map.DefaultedMap defaultedMap48 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set49 = defaultedMap48.keySet();
        java.lang.Object obj51 = defaultedMap48.get((java.lang.Object) 10L);
        collections.map.DefaultedMap defaultedMap53 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj55 = defaultedMap53.remove((java.lang.Object) 1.0f);
        java.lang.Object obj57 = defaultedMap53.remove((java.lang.Object) 'a');
        defaultedMap48.putAll((java.util.Map) defaultedMap53);
        collections.Predicate predicate59 = null;
        collections.Predicate predicate60 = null;
        java.util.Map map61 = collections.map.PredicatedMap.decorate((java.util.Map) defaultedMap48, predicate59, predicate60);
        boolean b62 = defaultedMap48.isEmpty();
        collections.map.DefaultedMap defaultedMap64 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj66 = defaultedMap64.get((java.lang.Object) 0.0f);
        boolean b67 = defaultedMap64.isEmpty();
        java.lang.Object obj70 = defaultedMap64.put((java.lang.Object) 10L, (java.lang.Object) "{}");
        collections.map.DefaultedMap defaultedMap71 = new collections.map.DefaultedMap((java.lang.Object) defaultedMap64);
        java.util.Set set72 = defaultedMap64.entrySet();
        boolean b73 = defaultedMap48.equals((java.lang.Object) defaultedMap64);
        java.util.Set set74 = defaultedMap64.entrySet();
        java.lang.Object obj75 = defaultedMap43.get((java.lang.Object) defaultedMap64);
        org.junit.Assert.assertNotNull(set2);
        org.junit.Assert.assertNotNull(collection3);
        org.junit.Assert.assertNotNull(set6);
        org.junit.Assert.assertTrue(b8 == false);
        org.junit.Assert.assertNotNull(collection9);
        org.junit.Assert.assertTrue(b11 == true);
        org.junit.Assert.assertTrue(b12 == false);
        org.junit.Assert.assertNotNull(set15);
        org.junit.Assert.assertTrue(b17 == false);
        org.junit.Assert.assertNotNull(collection18);
        org.junit.Assert.assertNull(obj23);
        org.junit.Assert.assertNull(obj28);
        org.junit.Assert.assertNull(obj33);
        org.junit.Assert.assertTrue(b35 == true);
        org.junit.Assert.assertNull(obj37);
        org.junit.Assert.assertTrue(b39 == false);
        org.junit.Assert.assertNotNull(set40);
        org.junit.Assert.assertNull(obj41);
        org.junit.Assert.assertTrue(b44 == true);
        org.junit.Assert.assertTrue(b45 == true);
        org.junit.Assert.assertNull(obj46);
        org.junit.Assert.assertNotNull(set49);
        org.junit.Assert.assertTrue("'" + obj51 + "' != '" + (byte) 0 + "'", obj51.equals((byte) 0));
        org.junit.Assert.assertNull(obj55);
        org.junit.Assert.assertNull(obj57);
        org.junit.Assert.assertNotNull(map61);
        org.junit.Assert.assertTrue(b62 == true);
        org.junit.Assert.assertTrue("'" + obj66 + "' != '" + (byte) 0 + "'", obj66.equals((byte) 0));
        org.junit.Assert.assertTrue(b67 == true);
        org.junit.Assert.assertNull(obj70);
        org.junit.Assert.assertNotNull(set72);
        org.junit.Assert.assertTrue(b73 == false);
        org.junit.Assert.assertNotNull(set74);
        org.junit.Assert.assertTrue("'" + obj75 + "' != '" + (byte) 0 + "'", obj75.equals((byte) 0));
    }

    @Test
    public void test4() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test4");
        collections.map.DefaultedMap defaultedMap1 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj3 = null;
        java.lang.Object obj4 = defaultedMap1.put((java.lang.Object) 1, obj3);
        boolean b6 = defaultedMap1.containsKey((java.lang.Object) 1);
        java.lang.Object obj8 = defaultedMap1.remove((java.lang.Object) false);
        java.util.Set set9 = defaultedMap1.entrySet();
        org.junit.Assert.assertNull(obj4);
        org.junit.Assert.assertTrue(b6 == true);
        org.junit.Assert.assertNull(obj8);
        org.junit.Assert.assertNotNull(set9);
    }

    @Test
    public void test5() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test5");
        collections.map.DefaultedMap defaultedMap1 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj3 = defaultedMap1.get((java.lang.Object) 0.0f);
        boolean b4 = defaultedMap1.isEmpty();
        collections.map.DefaultedMap defaultedMap6 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        boolean b7 = defaultedMap6.isEmpty();
        boolean b8 = defaultedMap6.isEmpty();
        collections.map.DefaultedMap defaultedMap10 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set11 = defaultedMap10.keySet();
        boolean b13 = defaultedMap10.containsKey((java.lang.Object) 0.0f);
        boolean b14 = defaultedMap6.containsKey((java.lang.Object) 0.0f);
        java.util.Map map15 = collections.map.DefaultedMap.decorate((java.util.Map) defaultedMap1, (java.lang.Object) defaultedMap6);
        java.util.Collection collection16 = defaultedMap6.values();
        collections.map.DefaultedMap defaultedMap18 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Collection collection19 = defaultedMap18.values();
        boolean b20 = defaultedMap6.equals((java.lang.Object) defaultedMap18);
        collections.map.DefaultedMap defaultedMap22 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj24 = defaultedMap22.remove((java.lang.Object) 1.0f);
        java.lang.Object obj26 = defaultedMap22.remove((java.lang.Object) 'a');
        collections.map.DefaultedMap defaultedMap28 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj30 = defaultedMap28.remove((java.lang.Object) 1.0f);
        java.lang.Object obj32 = defaultedMap28.remove((java.lang.Object) 'a');
        java.lang.Object obj33 = defaultedMap22.get((java.lang.Object) 'a');
        defaultedMap22.clear();
        boolean b35 = defaultedMap22.isEmpty();
        java.util.Collection collection36 = defaultedMap22.values();
        boolean b37 = defaultedMap6.equals((java.lang.Object) collection36);
        defaultedMap6.clear();
        org.junit.Assert.assertTrue("'" + obj3 + "' != '" + (byte) 0 + "'", obj3.equals((byte) 0));
        org.junit.Assert.assertTrue(b4 == true);
        org.junit.Assert.assertTrue(b7 == true);
        org.junit.Assert.assertTrue(b8 == true);
        org.junit.Assert.assertNotNull(set11);
        org.junit.Assert.assertTrue(b13 == false);
        org.junit.Assert.assertTrue(b14 == false);
        org.junit.Assert.assertNotNull(map15);
        org.junit.Assert.assertNotNull(collection16);
        org.junit.Assert.assertNotNull(collection19);
        org.junit.Assert.assertTrue(b20 == true);
        org.junit.Assert.assertNull(obj24);
        org.junit.Assert.assertNull(obj26);
        org.junit.Assert.assertNull(obj30);
        org.junit.Assert.assertNull(obj32);
        org.junit.Assert.assertTrue("'" + obj33 + "' != '" + (byte) 0 + "'", obj33.equals((byte) 0));
        org.junit.Assert.assertTrue(b35 == true);
        org.junit.Assert.assertNotNull(collection36);
        org.junit.Assert.assertTrue(b37 == false);
    }

    @Test
    public void test6() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test6");
        collections.map.DefaultedMap defaultedMap1 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set2 = defaultedMap1.keySet();
        java.lang.Object obj4 = defaultedMap1.get((java.lang.Object) 10L);
        collections.map.DefaultedMap defaultedMap6 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj8 = defaultedMap6.remove((java.lang.Object) 1.0f);
        java.lang.Object obj10 = defaultedMap6.remove((java.lang.Object) 'a');
        defaultedMap1.putAll((java.util.Map) defaultedMap6);
        collections.Predicate predicate12 = null;
        collections.Predicate predicate13 = null;
        java.util.Map map14 = collections.map.PredicatedMap.decorate((java.util.Map) defaultedMap1, predicate12, predicate13);
        boolean b15 = defaultedMap1.isEmpty();
        collections.map.DefaultedMap defaultedMap17 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj19 = defaultedMap17.get((java.lang.Object) 0.0f);
        boolean b20 = defaultedMap17.isEmpty();
        java.lang.Object obj23 = defaultedMap17.put((java.lang.Object) 10L, (java.lang.Object) "{}");
        collections.map.DefaultedMap defaultedMap24 = new collections.map.DefaultedMap((java.lang.Object) defaultedMap17);
        java.util.Set set25 = defaultedMap17.entrySet();
        boolean b26 = defaultedMap1.equals((java.lang.Object) defaultedMap17);
        collections.map.DefaultedMap defaultedMap28 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj30 = null;
        java.lang.Object obj31 = defaultedMap28.put((java.lang.Object) 1, obj30);
        java.util.Set set32 = defaultedMap28.keySet();
        collections.map.DefaultedMap defaultedMap34 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj36 = defaultedMap34.remove((java.lang.Object) 1.0f);
        defaultedMap34.clear();
        collections.map.DefaultedMap defaultedMap39 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj41 = defaultedMap39.remove((java.lang.Object) 1.0f);
        collections.map.DefaultedMap defaultedMap43 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj45 = null;
        java.lang.Object obj46 = defaultedMap43.put((java.lang.Object) 1, obj45);
        boolean b48 = defaultedMap43.containsKey((java.lang.Object) 1);
        defaultedMap43.clear();
        java.lang.Object obj50 = defaultedMap34.put((java.lang.Object) defaultedMap39, (java.lang.Object) defaultedMap43);
        defaultedMap28.putAll((java.util.Map) defaultedMap39);
        java.lang.Object obj52 = null;
        boolean b53 = defaultedMap39.containsValue(obj52);
        collections.map.DefaultedMap defaultedMap55 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj57 = defaultedMap55.remove((java.lang.Object) 1.0f);
        defaultedMap55.clear();
        collections.map.DefaultedMap defaultedMap60 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj62 = defaultedMap60.remove((java.lang.Object) 1.0f);
        collections.map.DefaultedMap defaultedMap64 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj66 = null;
        java.lang.Object obj67 = defaultedMap64.put((java.lang.Object) 1, obj66);
        boolean b69 = defaultedMap64.containsKey((java.lang.Object) 1);
        defaultedMap64.clear();
        java.lang.Object obj71 = defaultedMap55.put((java.lang.Object) defaultedMap60, (java.lang.Object) defaultedMap64);
        defaultedMap39.putAll((java.util.Map) defaultedMap60);
        java.util.Collection collection73 = defaultedMap60.values();
        java.util.Map map74 = collections.map.DefaultedMap.decorate((java.util.Map) defaultedMap17, (java.lang.Object) collection73);
        collections.map.DefaultedMap defaultedMap76 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj78 = defaultedMap76.remove((java.lang.Object) 1.0f);
        java.util.Set set79 = defaultedMap76.keySet();
        int i80 = defaultedMap76.size();
        boolean b81 = defaultedMap17.containsValue((java.lang.Object) defaultedMap76);
        org.junit.Assert.assertNotNull(set2);
        org.junit.Assert.assertTrue("'" + obj4 + "' != '" + (byte) 0 + "'", obj4.equals((byte) 0));
        org.junit.Assert.assertNull(obj8);
        org.junit.Assert.assertNull(obj10);
        org.junit.Assert.assertNotNull(map14);
        org.junit.Assert.assertTrue(b15 == true);
        org.junit.Assert.assertTrue("'" + obj19 + "' != '" + (byte) 0 + "'", obj19.equals((byte) 0));
        org.junit.Assert.assertTrue(b20 == true);
        org.junit.Assert.assertNull(obj23);
        org.junit.Assert.assertNotNull(set25);
        org.junit.Assert.assertTrue(b26 == false);
        org.junit.Assert.assertNull(obj31);
        org.junit.Assert.assertNotNull(set32);
        org.junit.Assert.assertNull(obj36);
        org.junit.Assert.assertNull(obj41);
        org.junit.Assert.assertNull(obj46);
        org.junit.Assert.assertTrue(b48 == true);
        org.junit.Assert.assertNull(obj50);
        org.junit.Assert.assertTrue(b53 == false);
        org.junit.Assert.assertNull(obj57);
        org.junit.Assert.assertNull(obj62);
        org.junit.Assert.assertNull(obj67);
        org.junit.Assert.assertTrue(b69 == true);
        org.junit.Assert.assertNull(obj71);
        org.junit.Assert.assertNotNull(collection73);
        org.junit.Assert.assertNotNull(map74);
        org.junit.Assert.assertNull(obj78);
        org.junit.Assert.assertNotNull(set79);
        org.junit.Assert.assertTrue(i80 == 0);
        org.junit.Assert.assertTrue(b81 == false);
    }

    @Test
    public void test7() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test7");
        collections.map.DefaultedMap defaultedMap1 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set2 = defaultedMap1.keySet();
        boolean b4 = defaultedMap1.containsKey((java.lang.Object) 0.0f);
        java.util.Collection collection5 = defaultedMap1.values();
        collections.map.DefaultedMap defaultedMap6 = new collections.map.DefaultedMap((java.lang.Object) collection5);
        boolean b7 = defaultedMap6.isEmpty();
        collections.map.DefaultedMap defaultedMap9 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj11 = defaultedMap9.remove((java.lang.Object) 1.0f);
        defaultedMap9.clear();
        collections.map.DefaultedMap defaultedMap14 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj16 = defaultedMap14.remove((java.lang.Object) 1.0f);
        collections.map.DefaultedMap defaultedMap18 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj20 = null;
        java.lang.Object obj21 = defaultedMap18.put((java.lang.Object) 1, obj20);
        boolean b23 = defaultedMap18.containsKey((java.lang.Object) 1);
        defaultedMap18.clear();
        java.lang.Object obj25 = defaultedMap9.put((java.lang.Object) defaultedMap14, (java.lang.Object) defaultedMap18);
        collections.Predicate predicate26 = null;
        collections.Predicate predicate27 = null;
        java.util.Map map28 = collections.map.PredicatedMap.decorate((java.util.Map) defaultedMap9, predicate26, predicate27);
        java.lang.Object obj29 = defaultedMap6.get((java.lang.Object) predicate26);
        java.util.Set set30 = defaultedMap6.entrySet();
        collections.map.DefaultedMap defaultedMap32 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        boolean b33 = defaultedMap32.isEmpty();
        java.util.Set set34 = defaultedMap32.entrySet();
        collections.map.DefaultedMap defaultedMap36 = new collections.map.DefaultedMap((java.lang.Object) 0);
        boolean b37 = defaultedMap32.equals((java.lang.Object) 0);
        boolean b38 = defaultedMap6.containsKey((java.lang.Object) 0);
        collections.map.DefaultedMap defaultedMap40 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        boolean b41 = defaultedMap40.isEmpty();
        boolean b42 = defaultedMap40.isEmpty();
        collections.map.DefaultedMap defaultedMap44 = new collections.map.DefaultedMap((java.lang.Object) 0);
        java.lang.Object obj47 = defaultedMap44.put((java.lang.Object) (-1.0d), (java.lang.Object) '4');
        collections.map.DefaultedMap defaultedMap49 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj51 = null;
        java.lang.Object obj52 = defaultedMap49.put((java.lang.Object) 1, obj51);
        boolean b54 = defaultedMap49.containsKey((java.lang.Object) 1);
        defaultedMap49.clear();
        collections.map.DefaultedMap defaultedMap57 = new collections.map.DefaultedMap((java.lang.Object) 0);
        java.lang.Object obj59 = defaultedMap57.remove((java.lang.Object) (byte) 100);
        int i60 = defaultedMap57.size();
        java.lang.Object obj61 = defaultedMap49.remove((java.lang.Object) defaultedMap57);
        boolean b62 = defaultedMap44.containsKey((java.lang.Object) defaultedMap49);
        java.lang.Object obj63 = defaultedMap40.remove((java.lang.Object) defaultedMap44);
        defaultedMap40.clear();
        java.util.Set set65 = defaultedMap40.entrySet();
        boolean b66 = defaultedMap6.containsValue((java.lang.Object) defaultedMap40);
        collections.map.DefaultedMap defaultedMap67 = new collections.map.DefaultedMap((java.lang.Object) b66);
        java.util.Collection collection68 = defaultedMap67.values();
        org.junit.Assert.assertNotNull(set2);
        org.junit.Assert.assertTrue(b4 == false);
        org.junit.Assert.assertNotNull(collection5);
        org.junit.Assert.assertTrue(b7 == true);
        org.junit.Assert.assertNull(obj11);
        org.junit.Assert.assertNull(obj16);
        org.junit.Assert.assertNull(obj21);
        org.junit.Assert.assertTrue(b23 == true);
        org.junit.Assert.assertNull(obj25);
        org.junit.Assert.assertNotNull(map28);
        org.junit.Assert.assertNotNull(obj29);
        org.junit.Assert.assertNotNull(set30);
        org.junit.Assert.assertTrue(b33 == true);
        org.junit.Assert.assertNotNull(set34);
        org.junit.Assert.assertTrue(b37 == false);
        org.junit.Assert.assertTrue(b38 == false);
        org.junit.Assert.assertTrue(b41 == true);
        org.junit.Assert.assertTrue(b42 == true);
        org.junit.Assert.assertNull(obj47);
        org.junit.Assert.assertNull(obj52);
        org.junit.Assert.assertTrue(b54 == true);
        org.junit.Assert.assertNull(obj59);
        org.junit.Assert.assertTrue(i60 == 0);
        org.junit.Assert.assertNull(obj61);
        org.junit.Assert.assertTrue(b62 == false);
        org.junit.Assert.assertNull(obj63);
        org.junit.Assert.assertNotNull(set65);
        org.junit.Assert.assertTrue(b66 == false);
        org.junit.Assert.assertNotNull(collection68);
    }

    @Test
    public void test8() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test8");
        collections.map.DefaultedMap defaultedMap1 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set2 = defaultedMap1.keySet();
        java.util.Collection collection3 = defaultedMap1.values();
        collections.map.DefaultedMap defaultedMap5 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set6 = defaultedMap5.keySet();
        boolean b8 = defaultedMap5.containsKey((java.lang.Object) 0.0f);
        java.util.Collection collection9 = defaultedMap5.values();
        collections.map.DefaultedMap defaultedMap10 = new collections.map.DefaultedMap((java.lang.Object) collection9);
        boolean b11 = defaultedMap10.isEmpty();
        boolean b12 = defaultedMap1.containsValue((java.lang.Object) defaultedMap10);
        int i13 = defaultedMap10.size();
        defaultedMap10.clear();
        collections.map.DefaultedMap defaultedMap16 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set17 = defaultedMap16.keySet();
        collections.map.DefaultedMap defaultedMap19 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set20 = defaultedMap19.keySet();
        boolean b22 = defaultedMap19.containsKey((java.lang.Object) 0.0f);
        java.util.Collection collection23 = defaultedMap19.values();
        collections.map.DefaultedMap defaultedMap24 = new collections.map.DefaultedMap((java.lang.Object) collection23);
        boolean b25 = defaultedMap24.isEmpty();
        java.lang.Object obj26 = defaultedMap16.get((java.lang.Object) defaultedMap24);
        boolean b27 = defaultedMap10.containsValue((java.lang.Object) defaultedMap24);
        java.util.Collection collection28 = defaultedMap24.values();
        collections.map.DefaultedMap defaultedMap29 = new collections.map.DefaultedMap((java.lang.Object) defaultedMap24);
        java.util.Set set30 = defaultedMap24.keySet();
        java.lang.Object obj32 = defaultedMap24.get((java.lang.Object) (short) 1);
        collections.map.DefaultedMap defaultedMap34 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj36 = null;
        java.lang.Object obj37 = defaultedMap34.put((java.lang.Object) 1, obj36);
        boolean b39 = defaultedMap34.containsKey((java.lang.Object) 1);
        int i40 = defaultedMap34.size();
        collections.map.DefaultedMap defaultedMap42 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Set set43 = defaultedMap42.keySet();
        boolean b45 = defaultedMap42.containsKey((java.lang.Object) 0.0f);
        java.util.Collection collection46 = defaultedMap42.values();
        collections.map.DefaultedMap defaultedMap47 = new collections.map.DefaultedMap((java.lang.Object) collection46);
        boolean b48 = defaultedMap47.isEmpty();
        collections.map.DefaultedMap defaultedMap50 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj52 = defaultedMap50.remove((java.lang.Object) 1.0f);
        defaultedMap50.clear();
        collections.map.DefaultedMap defaultedMap55 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj57 = defaultedMap55.remove((java.lang.Object) 1.0f);
        collections.map.DefaultedMap defaultedMap59 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj61 = null;
        java.lang.Object obj62 = defaultedMap59.put((java.lang.Object) 1, obj61);
        boolean b64 = defaultedMap59.containsKey((java.lang.Object) 1);
        defaultedMap59.clear();
        java.lang.Object obj66 = defaultedMap50.put((java.lang.Object) defaultedMap55, (java.lang.Object) defaultedMap59);
        collections.Predicate predicate67 = null;
        collections.Predicate predicate68 = null;
        java.util.Map map69 = collections.map.PredicatedMap.decorate((java.util.Map) defaultedMap50, predicate67, predicate68);
        java.lang.Object obj70 = defaultedMap47.get((java.lang.Object) predicate67);
        collections.map.DefaultedMap defaultedMap72 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.lang.Object obj74 = null;
        java.lang.Object obj75 = defaultedMap72.put((java.lang.Object) 1, obj74);
        java.util.Set set76 = defaultedMap72.keySet();
        boolean b77 = defaultedMap47.containsValue((java.lang.Object) set76);
        collections.map.DefaultedMap defaultedMap79 = new collections.map.DefaultedMap((java.lang.Object) (byte) 0);
        java.util.Collection collection80 = defaultedMap79.values();
        java.lang.Object obj81 = defaultedMap34.put((java.lang.Object) b77, (java.lang.Object) defaultedMap79);
        collections.map.DefaultedMap defaultedMap82 = new collections.map.DefaultedMap((java.lang.Object) defaultedMap79);
        collections.Predicate predicate83 = null;
        collections.Predicate predicate84 = null;
        java.util.Map map85 = collections.map.PredicatedMap.decorate((java.util.Map) defaultedMap82, predicate83, predicate84);
        boolean b86 = defaultedMap24.containsValue((java.lang.Object) predicate84);
        org.junit.Assert.assertNotNull(set2);
        org.junit.Assert.assertNotNull(collection3);
        org.junit.Assert.assertNotNull(set6);
        org.junit.Assert.assertTrue(b8 == false);
        org.junit.Assert.assertNotNull(collection9);
        org.junit.Assert.assertTrue(b11 == true);
        org.junit.Assert.assertTrue(b12 == false);
        org.junit.Assert.assertTrue(i13 == 0);
        org.junit.Assert.assertNotNull(set17);
        org.junit.Assert.assertNotNull(set20);
        org.junit.Assert.assertTrue(b22 == false);
        org.junit.Assert.assertNotNull(collection23);
        org.junit.Assert.assertTrue(b25 == true);
        org.junit.Assert.assertTrue("'" + obj26 + "' != '" + (byte) 0 + "'", obj26.equals((byte) 0));
        org.junit.Assert.assertTrue(b27 == false);
        org.junit.Assert.assertNotNull(collection28);
        org.junit.Assert.assertNotNull(set30);
        org.junit.Assert.assertNotNull(obj32);
        org.junit.Assert.assertNull(obj37);
        org.junit.Assert.assertTrue(b39 == true);
        org.junit.Assert.assertTrue(i40 == 1);
        org.junit.Assert.assertNotNull(set43);
        org.junit.Assert.assertTrue(b45 == false);
        org.junit.Assert.assertNotNull(collection46);
        org.junit.Assert.assertTrue(b48 == true);
        org.junit.Assert.assertNull(obj52);
        org.junit.Assert.assertNull(obj57);
        org.junit.Assert.assertNull(obj62);
        org.junit.Assert.assertTrue(b64 == true);
        org.junit.Assert.assertNull(obj66);
        org.junit.Assert.assertNotNull(map69);
        org.junit.Assert.assertNotNull(obj70);
        org.junit.Assert.assertNull(obj75);
        org.junit.Assert.assertNotNull(set76);
        org.junit.Assert.assertTrue(b77 == false);
        org.junit.Assert.assertNotNull(collection80);
        org.junit.Assert.assertNull(obj81);
        org.junit.Assert.assertNotNull(map85);
        org.junit.Assert.assertTrue(b86 == false);
    }
}

