/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 08 16:02:04 GMT 2017
 */

package collections.iterators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import collections.Predicate;
import collections.functors.NotNullPredicate;
import collections.iterators.FilterIterator;
import java.util.Iterator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class FilterIterator_ESTest extends FilterIterator_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 23 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch
   * Goal 3. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 4. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 5. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 6. Branch collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch in context: collections.iterators.FilterIterator:getPredicate()Lcollections/Predicate;
   * Goal 7. [Output]: collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;:NonNull
   * Goal 8. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 12. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 13. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 14. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 15. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: Line 140
   * Goal 16. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 17. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 18. [METHOD] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   * Goal 19. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 20. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 21. [METHODNOEX] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   * Goal 22. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   * Goal 23. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      NotNullPredicate notNullPredicate0 = (NotNullPredicate)NotNullPredicate.INSTANCE;
      FilterIterator filterIterator1 = new FilterIterator((Iterator) filterIterator0, (Predicate) notNullPredicate0);
      NotNullPredicate notNullPredicate1 = (NotNullPredicate)filterIterator1.getPredicate();
      assertSame(notNullPredicate0, notNullPredicate1);
  }

  //Test case number: 1
  /*
   * 19 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true
   * Goal 3. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 4. Branch collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true in context: collections.iterators.FilterIterator:hasNext()Z
   * Goal 5. hasNext()Z_java.lang.NullPointerException_IMPLICIT
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 11. collections.iterators.FilterIterator.hasNext()Z: Line 69
   * Goal 12. collections.iterators.FilterIterator.hasNext()Z: Line 72
   * Goal 13. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 14. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 15. [METHOD] collections.iterators.FilterIterator.hasNext()Z
   * Goal 16. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 17. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 18. Weak Mutation 3: collections.iterators.FilterIterator.hasNext()Z:69 - InsertUnaryOp Negation
   * Goal 19. Weak Mutation 4: collections.iterators.FilterIterator.hasNext()Z:69 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator((Iterator) null);
      // Undeclared exception!
      try { 
        filterIterator0.hasNext();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("collections.iterators.FilterIterator", e);
      }
  }

  //Test case number: 2
  /*
   * 17 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true
   * Goal 3. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 4. Branch collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true in context: collections.iterators.FilterIterator:remove()V
   * Goal 5. remove()V_java.lang.NullPointerException_IMPLICIT
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 10. collections.iterators.FilterIterator.remove()V: Line 105
   * Goal 11. collections.iterators.FilterIterator.remove()V: Line 108
   * Goal 12. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 13. [METHOD] collections.iterators.FilterIterator.remove()V
   * Goal 14. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 15. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 10: collections.iterators.FilterIterator.remove()V:105 - InsertUnaryOp Negation
   * Goal 17. Weak Mutation 11: collections.iterators.FilterIterator.remove()V:105 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      // Undeclared exception!
      try { 
        filterIterator0.remove();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("collections.iterators.FilterIterator", e);
      }
  }

  //Test case number: 3
  /*
   * 31 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 3. collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true
   * Goal 4. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false
   * Goal 5. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 6. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 7. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 8. next()Ljava/lang/Object;_java.lang.NullPointerException_IMPLICIT
   * Goal 9. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 10. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 12. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 13. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 14. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 15. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 16. collections.iterators.FilterIterator.hasNext()Z: Line 69
   * Goal 17. collections.iterators.FilterIterator.hasNext()Z: Line 72
   * Goal 18. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 87
   * Goal 19. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 88
   * Goal 20. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 21. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 22. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 23. [METHOD] collections.iterators.FilterIterator.next()Ljava/lang/Object;
   * Goal 24. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 25. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 26. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   * Goal 27. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 28. Weak Mutation 3: collections.iterators.FilterIterator.hasNext()Z:69 - InsertUnaryOp Negation
   * Goal 29. Weak Mutation 4: collections.iterators.FilterIterator.hasNext()Z:69 - ReplaceComparisonOperator == -> !=
   * Goal 30. Weak Mutation 6: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - InsertUnaryOp Negation
   * Goal 31. Weak Mutation 7: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - ReplaceComparisonOperator != -> ==
   */

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      FilterIterator filterIterator1 = new FilterIterator((Iterator) filterIterator0, (Predicate) null);
      // Undeclared exception!
      try { 
        filterIterator1.next();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("collections.iterators.FilterIterator", e);
      }
  }

  //Test case number: 4
  /*
   * 19 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: root-Branch
   * Goal 3. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 4. Branch collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:setIterator(Ljava/util/Iterator;)V
   * Goal 5. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 6. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 10. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 128
   * Goal 11. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 129
   * Goal 12. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 130
   * Goal 13. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 131
   * Goal 14. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 15. [METHOD] collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V
   * Goal 16. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 17. [METHODNOEX] collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V
   * Goal 18. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 19. Weak Mutation 14: collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V:130 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator((Iterator) null);
      filterIterator0.setIterator((Iterator) null);
  }

  //Test case number: 5
  /*
   * 18 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: root-Branch
   * Goal 3. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 4. Branch collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:setPredicate(Lcollections/Predicate;)V
   * Goal 5. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 9. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 150
   * Goal 10. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 151
   * Goal 11. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 152
   * Goal 12. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 153
   * Goal 13. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 14. [METHOD] collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V
   * Goal 15. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 16. [METHODNOEX] collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V
   * Goal 17. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   * Goal 18. Weak Mutation 15: collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V:152 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      NotNullPredicate notNullPredicate0 = (NotNullPredicate)NotNullPredicate.INSTANCE;
      filterIterator0.setPredicate(notNullPredicate0);
  }

  //Test case number: 6
  /*
   * 23 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch
   * Goal 3. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 4. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 5. Branch collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch in context: collections.iterators.FilterIterator:getIterator()Ljava/util/Iterator;
   * Goal 6. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 7. [Output]: collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;:NonNull
   * Goal 8. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 12. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 13. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 14. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 15. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: Line 118
   * Goal 16. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 17. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 18. [METHOD] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 19. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 20. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 21. [METHODNOEX] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 22. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   * Goal 23. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      NotNullPredicate notNullPredicate0 = (NotNullPredicate)NotNullPredicate.INSTANCE;
      FilterIterator filterIterator1 = new FilterIterator((Iterator) filterIterator0, (Predicate) notNullPredicate0);
      Iterator iterator0 = filterIterator1.getIterator();
      assertSame(filterIterator0, iterator0);
  }

  //Test case number: 7
  /*
   * 15 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch
   * Goal 3. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 4. Branch collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch in context: collections.iterators.FilterIterator:getIterator()Ljava/util/Iterator;
   * Goal 5. [Output]: collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;:Null
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 10. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: Line 118
   * Goal 11. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 12. [METHOD] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 13. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 14. [METHODNOEX] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 15. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      Iterator iterator0 = filterIterator0.getIterator();
      assertNull(iterator0);
  }

  //Test case number: 8
  /*
   * 15 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch
   * Goal 3. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 4. Branch collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch in context: collections.iterators.FilterIterator:getPredicate()Lcollections/Predicate;
   * Goal 5. [Output]: collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;:Null
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 10. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: Line 140
   * Goal 11. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 12. [METHOD] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   * Goal 13. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 14. [METHODNOEX] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   * Goal 15. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      NotNullPredicate notNullPredicate0 = (NotNullPredicate)filterIterator0.getPredicate();
      assertNull(notNullPredicate0);
  }
}
