/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 08 15:29:52 GMT 2017
 */

package collections.iterators;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import collections.Predicate;
import collections.functors.AllPredicate;
import collections.functors.InstanceofPredicate;
import collections.functors.TruePredicate;
import collections.functors.UniquePredicate;
import collections.iterators.FilterIterator;
import java.util.ConcurrentModificationException;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.ListIterator;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class FilterIterator_ESTest extends FilterIterator_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 15 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch
   * Goal 3. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 4. Branch collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch in context: collections.iterators.FilterIterator:getPredicate()Lcollections/Predicate;
   * Goal 5. [Output]: collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;:Null
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 10. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: Line 140
   * Goal 11. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 12. [METHOD] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   * Goal 13. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 14. [METHODNOEX] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   * Goal 15. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      Predicate predicate0 = filterIterator0.getPredicate();
      assertNull(predicate0);
  }

  //Test case number: 1
  /*
   * 23 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch
   * Goal 3. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 4. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 5. Branch collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch in context: collections.iterators.FilterIterator:getIterator()Ljava/util/Iterator;
   * Goal 6. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 7. [Output]: collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;:NonNull
   * Goal 8. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 12. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 13. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 14. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 15. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: Line 118
   * Goal 16. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 17. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 18. [METHOD] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 19. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 20. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 21. [METHODNOEX] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 22. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   * Goal 23. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      UniquePredicate uniquePredicate0 = (UniquePredicate)UniquePredicate.getInstance();
      FilterIterator filterIterator1 = new FilterIterator((Iterator) filterIterator0, (Predicate) uniquePredicate0);
      Iterator iterator0 = filterIterator1.getIterator();
      assertSame(filterIterator0, iterator0);
  }

  //Test case number: 2
  /*
   * 19 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true
   * Goal 3. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 4. Branch collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true in context: collections.iterators.FilterIterator:remove()V
   * Goal 5. remove()V_java.util.ConcurrentModificationException_IMPLICIT
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 12. collections.iterators.FilterIterator.remove()V: Line 105
   * Goal 13. collections.iterators.FilterIterator.remove()V: Line 108
   * Goal 14. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 15. [METHOD] collections.iterators.FilterIterator.remove()V
   * Goal 16. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 17. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 18. Weak Mutation 10: collections.iterators.FilterIterator.remove()V:105 - InsertUnaryOp Negation
   * Goal 19. Weak Mutation 11: collections.iterators.FilterIterator.remove()V:105 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator(0);
      TruePredicate truePredicate0 = (TruePredicate)TruePredicate.getInstance();
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0, (Predicate) truePredicate0);
      Integer integer0 = new Integer(2439);
      linkedList0.add((Object) integer0);
      // Undeclared exception!
      try { 
        filterIterator0.remove();
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.LinkedList$ListItr", e);
      }
  }

  //Test case number: 3
  /*
   * 17 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true
   * Goal 3. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 4. Branch collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true in context: collections.iterators.FilterIterator:remove()V
   * Goal 5. remove()V_java.lang.NullPointerException_IMPLICIT
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 10. collections.iterators.FilterIterator.remove()V: Line 105
   * Goal 11. collections.iterators.FilterIterator.remove()V: Line 108
   * Goal 12. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 13. [METHOD] collections.iterators.FilterIterator.remove()V
   * Goal 14. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 15. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   * Goal 16. Weak Mutation 10: collections.iterators.FilterIterator.remove()V:105 - InsertUnaryOp Negation
   * Goal 17. Weak Mutation 11: collections.iterators.FilterIterator.remove()V:105 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      // Undeclared exception!
      try { 
        filterIterator0.remove();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("collections.iterators.FilterIterator", e);
      }
  }

  //Test case number: 4
  /*
   * 23 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false
   * Goal 3. collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false
   * Goal 4. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 5. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 6. Branch collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false in context: 
   * Goal 7. next()Ljava/lang/Object;_java.util.ConcurrentModificationException_IMPLICIT
   * Goal 8. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 12. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 13. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 87
   * Goal 14. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 88
   * Goal 15. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 16. collections.iterators.FilterIterator.setNextObject()Z: Line 165
   * Goal 17. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 18. [METHOD] collections.iterators.FilterIterator.next()Ljava/lang/Object;
   * Goal 19. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 20. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 21. Weak Mutation 6: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - InsertUnaryOp Negation
   * Goal 22. Weak Mutation 7: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - ReplaceComparisonOperator != -> ==
   * Goal 23. Weak Mutation 16: collections.iterators.FilterIterator.setNextObject()Z:164 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator();
      Integer integer0 = new Integer(170);
      linkedList0.add((Object) integer0);
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0);
      // Undeclared exception!
      try { 
        filterIterator0.next();
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.LinkedList$ListItr", e);
      }
  }

  //Test case number: 5
  /*
   * 18 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false
   * Goal 3. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 4. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 5. next()Ljava/lang/Object;_java.lang.NullPointerException_IMPLICIT
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 10. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 87
   * Goal 11. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 88
   * Goal 12. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 13. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 14. [METHOD] collections.iterators.FilterIterator.next()Ljava/lang/Object;
   * Goal 15. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 16. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   * Goal 17. Weak Mutation 6: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - InsertUnaryOp Negation
   * Goal 18. Weak Mutation 7: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - ReplaceComparisonOperator != -> ==
   */

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      // Undeclared exception!
      try { 
        filterIterator0.next();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("collections.iterators.FilterIterator", e);
      }
  }

  //Test case number: 6
  /*
   * 24 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true
   * Goal 3. collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false
   * Goal 4. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 5. Branch collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true in context: collections.iterators.FilterIterator:hasNext()Z
   * Goal 6. Branch collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false in context: 
   * Goal 7. hasNext()Z_java.util.ConcurrentModificationException_IMPLICIT
   * Goal 8. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 12. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 13. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 14. collections.iterators.FilterIterator.hasNext()Z: Line 69
   * Goal 15. collections.iterators.FilterIterator.hasNext()Z: Line 72
   * Goal 16. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 17. collections.iterators.FilterIterator.setNextObject()Z: Line 165
   * Goal 18. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 19. [METHOD] collections.iterators.FilterIterator.hasNext()Z
   * Goal 20. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 21. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 22. Weak Mutation 3: collections.iterators.FilterIterator.hasNext()Z:69 - InsertUnaryOp Negation
   * Goal 23. Weak Mutation 4: collections.iterators.FilterIterator.hasNext()Z:69 - ReplaceComparisonOperator == -> !=
   * Goal 24. Weak Mutation 16: collections.iterators.FilterIterator.setNextObject()Z:164 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator(0);
      Class<Object> class0 = Object.class;
      InstanceofPredicate instanceofPredicate0 = (InstanceofPredicate)InstanceofPredicate.getInstance(class0);
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0, (Predicate) instanceofPredicate0);
      linkedList0.add((Object) class0);
      // Undeclared exception!
      try { 
        filterIterator0.hasNext();
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.LinkedList$ListItr", e);
      }
  }

  //Test case number: 7
  /*
   * 18 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true
   * Goal 3. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 4. Branch collections.iterators.FilterIterator.remove()V: I4 Branch 4 IFEQ L105 - true in context: collections.iterators.FilterIterator:remove()V
   * Goal 5. remove()V_java.lang.IllegalStateException_IMPLICIT
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 11. collections.iterators.FilterIterator.remove()V: Line 105
   * Goal 12. collections.iterators.FilterIterator.remove()V: Line 108
   * Goal 13. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 14. [METHOD] collections.iterators.FilterIterator.remove()V
   * Goal 15. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 16. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 17. Weak Mutation 10: collections.iterators.FilterIterator.remove()V:105 - InsertUnaryOp Negation
   * Goal 18. Weak Mutation 11: collections.iterators.FilterIterator.remove()V:105 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Iterator<Object> iterator0 = linkedList0.descendingIterator();
      FilterIterator filterIterator0 = new FilterIterator(iterator0);
      // Undeclared exception!
      try { 
        filterIterator0.remove();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("java.util.LinkedList$ListItr", e);
      }
  }

  //Test case number: 8
  /*
   * 40 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false
   * Goal 3. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I9 Branch 3 IFNE L88 - true
   * Goal 4. collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false
   * Goal 5. collections.iterators.FilterIterator.setNextObject()Z: I18 Branch 6 IFEQ L166 - false
   * Goal 6. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 7. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 8. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I9 Branch 3 IFNE L88 - true in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 9. Branch collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false in context: 
   * Goal 10. Branch collections.iterators.FilterIterator.setNextObject()Z: I18 Branch 6 IFEQ L166 - false in context: 
   * Goal 11. [Output]: collections.iterators.FilterIterator.next()Ljava/lang/Object;:NonNull
   * Goal 12. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 13. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 14. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 15. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 16. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 17. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 18. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 87
   * Goal 19. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 88
   * Goal 20. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 92
   * Goal 21. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 93
   * Goal 22. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 23. collections.iterators.FilterIterator.setNextObject()Z: Line 165
   * Goal 24. collections.iterators.FilterIterator.setNextObject()Z: Line 166
   * Goal 25. collections.iterators.FilterIterator.setNextObject()Z: Line 167
   * Goal 26. collections.iterators.FilterIterator.setNextObject()Z: Line 168
   * Goal 27. collections.iterators.FilterIterator.setNextObject()Z: Line 169
   * Goal 28. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 29. [METHOD] collections.iterators.FilterIterator.next()Ljava/lang/Object;
   * Goal 30. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 31. [METHODNOEX] collections.iterators.FilterIterator.next()Ljava/lang/Object;
   * Goal 32. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 33. Weak Mutation 6: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - InsertUnaryOp Negation
   * Goal 34. Weak Mutation 7: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - ReplaceComparisonOperator != -> ==
   * Goal 35. Weak Mutation 8: collections.iterators.FilterIterator.next()Ljava/lang/Object;:88 - ReplaceComparisonOperator != -> ==
   * Goal 36. Weak Mutation 9: collections.iterators.FilterIterator.next()Ljava/lang/Object;:92 - ReplaceConstant - 0 -> 1
   * Goal 37. Weak Mutation 16: collections.iterators.FilterIterator.setNextObject()Z:164 - ReplaceComparisonOperator == -> !=
   * Goal 38. Weak Mutation 17: collections.iterators.FilterIterator.setNextObject()Z:166 - ReplaceComparisonOperator == -> !=
   * Goal 39. Weak Mutation 18: collections.iterators.FilterIterator.setNextObject()Z:168 - ReplaceConstant - 1 -> 0
   * Goal 40. Weak Mutation 19: collections.iterators.FilterIterator.setNextObject()Z:169 - ReplaceConstant - 1 -> 0
   */

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) linkedList0);
      ListIterator<Object> listIterator0 = linkedList0.listIterator(0);
      Predicate[] predicateArray0 = new Predicate[0];
      TruePredicate truePredicate0 = (TruePredicate)AllPredicate.getInstance(predicateArray0);
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0, (Predicate) truePredicate0);
      filterIterator0.next();
      assertTrue(listIterator0.hasPrevious());
      assertFalse(listIterator0.hasNext());
  }

  //Test case number: 9
  /*
   * 28 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false
   * Goal 3. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I9 Branch 3 IFNE L88 - false
   * Goal 4. collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - true
   * Goal 5. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 6. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - false in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 7. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I9 Branch 3 IFNE L88 - false in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 8. Branch collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - true in context: 
   * Goal 9. next()Ljava/lang/Object;_java.util.NoSuchElementException_EXPLICIT
   * Goal 10. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 12. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 13. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 14. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 15. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 87
   * Goal 16. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 88
   * Goal 17. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 89
   * Goal 18. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 19. collections.iterators.FilterIterator.setNextObject()Z: Line 172
   * Goal 20. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 21. [METHOD] collections.iterators.FilterIterator.next()Ljava/lang/Object;
   * Goal 22. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 23. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 24. Weak Mutation 6: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - InsertUnaryOp Negation
   * Goal 25. Weak Mutation 7: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - ReplaceComparisonOperator != -> ==
   * Goal 26. Weak Mutation 8: collections.iterators.FilterIterator.next()Ljava/lang/Object;:88 - ReplaceComparisonOperator != -> ==
   * Goal 27. Weak Mutation 16: collections.iterators.FilterIterator.setNextObject()Z:164 - ReplaceComparisonOperator == -> !=
   * Goal 28. Weak Mutation 20: collections.iterators.FilterIterator.setNextObject()Z:172 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Iterator<Object> iterator0 = linkedList0.descendingIterator();
      FilterIterator filterIterator0 = new FilterIterator(iterator0);
      // Undeclared exception!
      try { 
        filterIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("collections.iterators.FilterIterator", e);
      }
  }

  //Test case number: 10
  /*
   * 45 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true
   * Goal 3. collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - true
   * Goal 4. collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false
   * Goal 5. collections.iterators.FilterIterator.setNextObject()Z: I18 Branch 6 IFEQ L166 - false
   * Goal 6. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 7. Branch collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true in context: collections.iterators.FilterIterator:hasNext()Z
   * Goal 8. Branch collections.iterators.FilterIterator.next()Ljava/lang/Object;: I4 Branch 2 IFNE L87 - true in context: collections.iterators.FilterIterator:next()Ljava/lang/Object;
   * Goal 9. Branch collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - false in context: 
   * Goal 10. Branch collections.iterators.FilterIterator.setNextObject()Z: I18 Branch 6 IFEQ L166 - false in context: 
   * Goal 11. [Output]: collections.iterators.FilterIterator.hasNext()Z:True
   * Goal 12. [Output]: collections.iterators.FilterIterator.next()Ljava/lang/Object;:NonNull
   * Goal 13. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 14. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 15. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 16. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 17. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 18. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 19. collections.iterators.FilterIterator.hasNext()Z: Line 69
   * Goal 20. collections.iterators.FilterIterator.hasNext()Z: Line 72
   * Goal 21. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 87
   * Goal 22. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 92
   * Goal 23. collections.iterators.FilterIterator.next()Ljava/lang/Object;: Line 93
   * Goal 24. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 25. collections.iterators.FilterIterator.setNextObject()Z: Line 165
   * Goal 26. collections.iterators.FilterIterator.setNextObject()Z: Line 166
   * Goal 27. collections.iterators.FilterIterator.setNextObject()Z: Line 167
   * Goal 28. collections.iterators.FilterIterator.setNextObject()Z: Line 168
   * Goal 29. collections.iterators.FilterIterator.setNextObject()Z: Line 169
   * Goal 30. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 31. [METHOD] collections.iterators.FilterIterator.hasNext()Z
   * Goal 32. [METHOD] collections.iterators.FilterIterator.next()Ljava/lang/Object;
   * Goal 33. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 34. [METHODNOEX] collections.iterators.FilterIterator.hasNext()Z
   * Goal 35. [METHODNOEX] collections.iterators.FilterIterator.next()Ljava/lang/Object;
   * Goal 36. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 37. Weak Mutation 3: collections.iterators.FilterIterator.hasNext()Z:69 - InsertUnaryOp Negation
   * Goal 38. Weak Mutation 4: collections.iterators.FilterIterator.hasNext()Z:69 - ReplaceComparisonOperator == -> !=
   * Goal 39. Weak Mutation 6: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - InsertUnaryOp Negation
   * Goal 40. Weak Mutation 7: collections.iterators.FilterIterator.next()Ljava/lang/Object;:87 - ReplaceComparisonOperator != -> ==
   * Goal 41. Weak Mutation 9: collections.iterators.FilterIterator.next()Ljava/lang/Object;:92 - ReplaceConstant - 0 -> 1
   * Goal 42. Weak Mutation 16: collections.iterators.FilterIterator.setNextObject()Z:164 - ReplaceComparisonOperator == -> !=
   * Goal 43. Weak Mutation 17: collections.iterators.FilterIterator.setNextObject()Z:166 - ReplaceComparisonOperator == -> !=
   * Goal 44. Weak Mutation 18: collections.iterators.FilterIterator.setNextObject()Z:168 - ReplaceConstant - 1 -> 0
   * Goal 45. Weak Mutation 19: collections.iterators.FilterIterator.setNextObject()Z:169 - ReplaceConstant - 1 -> 0
   */

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      linkedList0.add((Object) linkedList0);
      ListIterator<Object> listIterator0 = linkedList0.listIterator(0);
      Class<Object> class0 = Object.class;
      InstanceofPredicate instanceofPredicate0 = (InstanceofPredicate)InstanceofPredicate.getInstance(class0);
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0, (Predicate) instanceofPredicate0);
      filterIterator0.hasNext();
      filterIterator0.next();
      assertFalse(listIterator0.hasNext());
      assertTrue(listIterator0.hasPrevious());
  }

  //Test case number: 11
  /*
   * 26 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true
   * Goal 3. collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - true
   * Goal 4. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 5. Branch collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true in context: collections.iterators.FilterIterator:hasNext()Z
   * Goal 6. Branch collections.iterators.FilterIterator.setNextObject()Z: I5 Branch 5 IFEQ L164 - true in context: 
   * Goal 7. [Output]: collections.iterators.FilterIterator.hasNext()Z:False
   * Goal 8. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 12. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 13. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 14. collections.iterators.FilterIterator.hasNext()Z: Line 69
   * Goal 15. collections.iterators.FilterIterator.hasNext()Z: Line 72
   * Goal 16. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 17. collections.iterators.FilterIterator.setNextObject()Z: Line 172
   * Goal 18. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 19. [METHOD] collections.iterators.FilterIterator.hasNext()Z
   * Goal 20. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 21. [METHODNOEX] collections.iterators.FilterIterator.hasNext()Z
   * Goal 22. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 23. Weak Mutation 3: collections.iterators.FilterIterator.hasNext()Z:69 - InsertUnaryOp Negation
   * Goal 24. Weak Mutation 4: collections.iterators.FilterIterator.hasNext()Z:69 - ReplaceComparisonOperator == -> !=
   * Goal 25. Weak Mutation 16: collections.iterators.FilterIterator.setNextObject()Z:164 - ReplaceComparisonOperator == -> !=
   * Goal 26. Weak Mutation 20: collections.iterators.FilterIterator.setNextObject()Z:172 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator(0);
      Class<Object> class0 = Object.class;
      InstanceofPredicate instanceofPredicate0 = (InstanceofPredicate)InstanceofPredicate.getInstance(class0);
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0, (Predicate) instanceofPredicate0);
      boolean boolean0 = filterIterator0.hasNext();
      assertFalse(boolean0);
  }

  //Test case number: 12
  /*
   * 20 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: root-Branch
   * Goal 3. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 4. Branch collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:setIterator(Ljava/util/Iterator;)V
   * Goal 5. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 6. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 11. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 128
   * Goal 12. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 129
   * Goal 13. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 130
   * Goal 14. collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V: Line 131
   * Goal 15. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 16. [METHOD] collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V
   * Goal 17. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 18. [METHODNOEX] collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V
   * Goal 19. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 20. Weak Mutation 14: collections.iterators.FilterIterator.setIterator(Ljava/util/Iterator;)V:130 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator(0);
      Class<Object> class0 = Object.class;
      InstanceofPredicate instanceofPredicate0 = (InstanceofPredicate)InstanceofPredicate.getInstance(class0);
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0, (Predicate) instanceofPredicate0);
      filterIterator0.setIterator(filterIterator0);
  }

  //Test case number: 13
  /*
   * 20 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: root-Branch
   * Goal 3. Branch collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:setPredicate(Lcollections/Predicate;)V
   * Goal 4. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 5. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 6. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 11. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 150
   * Goal 12. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 151
   * Goal 13. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 152
   * Goal 14. collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V: Line 153
   * Goal 15. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 16. [METHOD] collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V
   * Goal 17. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 18. [METHODNOEX] collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V
   * Goal 19. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   * Goal 20. Weak Mutation 15: collections.iterators.FilterIterator.setPredicate(Lcollections/Predicate;)V:152 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator(0);
      Predicate[] predicateArray0 = new Predicate[0];
      TruePredicate truePredicate0 = (TruePredicate)AllPredicate.getInstance(predicateArray0);
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0, (Predicate) truePredicate0);
      filterIterator0.setPredicate(truePredicate0);
  }

  //Test case number: 14
  /*
   * 16 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch
   * Goal 3. Branch collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: root-Branch in context: collections.iterators.FilterIterator:getIterator()Ljava/util/Iterator;
   * Goal 4. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;)V
   * Goal 5. [Output]: collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;:Null
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 45
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 46
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 11. collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;: Line 118
   * Goal 12. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 13. [METHOD] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 14. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V
   * Goal 15. [METHODNOEX] collections.iterators.FilterIterator.getIterator()Ljava/util/Iterator;
   * Goal 16. Weak Mutation 1: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V:24 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator((Iterator) null);
      Iterator iterator0 = filterIterator0.getIterator();
      assertNull(iterator0);
  }

  //Test case number: 15
  /*
   * 17 covered goals:
   * Goal 1. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch
   * Goal 2. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch
   * Goal 3. Branch collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: root-Branch in context: collections.iterators.FilterIterator:<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 4. Branch collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: root-Branch in context: collections.iterators.FilterIterator:getPredicate()Lcollections/Predicate;
   * Goal 5. [Output]: collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;:NonNull
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 57
   * Goal 10. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 58
   * Goal 11. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 59
   * Goal 12. collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;: Line 140
   * Goal 13. [METHOD] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 14. [METHOD] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   * Goal 15. [METHODNOEX] collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V
   * Goal 16. [METHODNOEX] collections.iterators.FilterIterator.getPredicate()Lcollections/Predicate;
   * Goal 17. Weak Mutation 2: collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V:24 - ReplaceConstant - 0 -> 1
   */

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      ListIterator<Object> listIterator0 = linkedList0.listIterator(0);
      Predicate[] predicateArray0 = new Predicate[0];
      TruePredicate truePredicate0 = (TruePredicate)AllPredicate.getInstance(predicateArray0);
      FilterIterator filterIterator0 = new FilterIterator((Iterator) listIterator0, (Predicate) truePredicate0);
      TruePredicate truePredicate1 = (TruePredicate)filterIterator0.getPredicate();
      assertSame(truePredicate0, truePredicate1);
  }

  //Test case number: 16
  /*
   * 18 covered goals:
   * Goal 1. collections.iterators.FilterIterator.<init>()V: root-Branch
   * Goal 2. collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true
   * Goal 3. Branch collections.iterators.FilterIterator.<init>()V: root-Branch in context: collections.iterators.FilterIterator:<init>()V
   * Goal 4. Branch collections.iterators.FilterIterator.hasNext()Z: I4 Branch 1 IFEQ L69 - true in context: collections.iterators.FilterIterator:hasNext()Z
   * Goal 5. hasNext()Z_java.lang.NullPointerException_IMPLICIT
   * Goal 6. collections.iterators.FilterIterator.<init>()V: Line 24
   * Goal 7. collections.iterators.FilterIterator.<init>()V: Line 34
   * Goal 8. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;)V: Line 24
   * Goal 9. collections.iterators.FilterIterator.<init>(Ljava/util/Iterator;Lcollections/Predicate;)V: Line 24
   * Goal 10. collections.iterators.FilterIterator.hasNext()Z: Line 69
   * Goal 11. collections.iterators.FilterIterator.hasNext()Z: Line 72
   * Goal 12. collections.iterators.FilterIterator.setNextObject()Z: Line 164
   * Goal 13. [METHOD] collections.iterators.FilterIterator.<init>()V
   * Goal 14. [METHOD] collections.iterators.FilterIterator.hasNext()Z
   * Goal 15. [METHODNOEX] collections.iterators.FilterIterator.<init>()V
   * Goal 16. Weak Mutation 0: collections.iterators.FilterIterator.<init>()V:24 - ReplaceConstant - 0 -> 1
   * Goal 17. Weak Mutation 3: collections.iterators.FilterIterator.hasNext()Z:69 - InsertUnaryOp Negation
   * Goal 18. Weak Mutation 4: collections.iterators.FilterIterator.hasNext()Z:69 - ReplaceComparisonOperator == -> !=
   */

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FilterIterator filterIterator0 = new FilterIterator();
      // Undeclared exception!
      try { 
        filterIterator0.hasNext();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("collections.iterators.FilterIterator", e);
      }
  }
}
